# Generated by Django 3.0.2 on 2020-01-30 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomitoryDays',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('day', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StaffDays',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('day', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentKinds',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('kinds', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentMenu',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('menu', models.TextField(null=True)),
                ('price', models.CharField(default='', max_length=255, null=True)),
                ('kinds_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.StudentKinds')),
            ],
        ),
        migrations.CreateModel(
            name='StaffMenu',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('time', models.CharField(default='', max_length=255, null=True)),
                ('menu', models.TextField(null=True)),
                ('day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.StaffDays')),
            ],
        ),
        migrations.CreateModel(
            name='DomitoryMenu',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('time', models.CharField(default='', max_length=255, null=True)),
                ('menu', models.TextField(null=True)),
                ('day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.DomitoryDays')),
            ],
        ),
    ]
