# Generated by Django 3.0.2 on 2020-01-30 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domitorymenu',
            old_name='day_id',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='staffmenu',
            old_name='day_id',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='studentmenu',
            old_name='kinds_id',
            new_name='kinds',
        ),
    ]
