version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    hostname: nginx
    networks:
      - backend
    ports:
      - "80:80"
    depends_on:
      - hanbat-server
    links:
      - hanbat-server



  hanbat-server:
    container_name: hanbat-server
    hostname: hanbat-server
    build: .
    command: "gunicorn hanbat.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    networks:
      - backend


networks:
  backend:
    driver: "bridge"